// ── CREATORS ──────────────────────────────────────────────────────────────────
export const CREATORS = [
  {
    id: "nicole-keshishian",
    name: "Nicole Keshishian",
    handle: "@kalejunkie",
    followers: "2.8M",
    bio: "Nourishing recipes for real life. Food that loves you back. Author of The Kalejunkie Cookbook. Based in Corte Madera, CA.",
    avatarUrl: "https://kalejunkie.com/wp-content/uploads/2025/09/main-image.webp",
    avatarColor: null,
    initials: "NK",
    topics: ["Nutrition", "Recipes", "Wellness"],
    socials: [{ label: "IG @kalejunkie", url: "https://instagram.com/kalejunkie" }, { label: "kalejunkie.com", url: "https://kalejunkie.com" }, { label: "Substack", url: "#" }],
    postCount: 12,
  },
  {
    id: "shira-gill",
    name: "Shira Gill",
    handle: "@shiragill",
    followers: "110K",
    bio: "Author, organizer, and minimalist living advocate. Helping you simplify your home, wardrobe, and life. Mill Valley, CA.",
    avatarUrl: "https://shiragill.com/wp-content/uploads/BeccaMeyerMillValley_7036-Edita-scaled.jpg",
    avatarColor: null,
    initials: "SG",
    topics: ["Lifestyle", "Wellness", "Home"],
    socials: [{ label: "IG @shiragill", url: "https://instagram.com/shiragill" }, { label: "shiragill.com", url: "https://shiragill.com" }],
    postCount: 8,
  },
  {
    id: "brit-morin",
    name: "Brit Morin",
    handle: "@brit",
    followers: "64.2K",
    bio: "Founder of Brit + Co. Investor. Podcast host. Helping women build brands and businesses they're proud of.",
    avatarUrl: "https://images.squarespace-cdn.com/content/v1/6303fb9404a0cf0cd130ef3c/f7b9ac1c-b3cb-42e6-aa9d-982f34d5507a/Brit+Morin+Headshot.jpg",
    avatarColor: null,
    initials: "BM",
    topics: ["Entrepreneurship", "Founder"],
    socials: [{ label: "IG @brit", url: "https://instagram.com/brit" }, { label: "brit.co", url: "https://brit.co" }],
    postCount: 5,
  },
  {
    id: "holly-blakey",
    name: "Holly Blakey",
    handle: "@breathing.room.home",
    followers: "329K",
    bio: "Interior designer and simplicity advocate. Creating calm, intentional homes for women who are done with clutter.",
    avatarUrl: "https://static1.squarespace.com/static/5b0b65b8f407b4a4414db2ee/5ea6de0a41e9232ab0a8b58d/639fd7597ca60c5b989498a5/1713378056113/Holly+June+20220467.jpg?format=1500w",
    avatarColor: null,
    initials: "HB",
    topics: ["Design", "Home", "Interior"],
    socials: [{ label: "IG @breathing.room.home", url: "https://instagram.com/breathing.room.home" }],
    postCount: 9,
  },
  {
    id: "kate-ogata",
    name: "Kate Ogata",
    handle: "@katieogata",
    followers: "122K",
    bio: "Certified strength coach specializing in women 40+. Evidence-based fitness without the punishment. Los Angeles, CA.",
    avatarUrl: null,
    avatarColor: "linear-gradient(135deg,#B5D5F7,#6098d8)",
    initials: "KO",
    topics: ["Fitness", "Wellness"],
    socials: [{ label: "IG @katieogata", url: "https://instagram.com/katieogata" }],
    postCount: 7,
  },
  {
    id: "amy-motroni",
    name: "Amy Motroni",
    handle: "@geniusmomhacks",
    followers: "339K",
    bio: "Helping busy moms simplify family life without losing their minds. Real tips, no guilt. San Jose, CA.",
    avatarUrl: "https://geniusmomhacks.com/wp-content/uploads/2023/11/Amy-Motroni.jpg",
    avatarColor: null,
    initials: "AM",
    topics: ["Parenthood", "Wellness"],
    socials: [{ label: "IG @geniusmomhacks", url: "https://instagram.com/geniusmomhacks" }, { label: "geniusmomhacks.com", url: "https://geniusmomhacks.com" }],
    postCount: 6,
  },
  {
    id: "caitlin-flemming",
    name: "Caitlin Flemming",
    handle: "@caitlinflemming",
    followers: "79.3K",
    bio: "Interior designer with a love for warm, livable spaces. Based in Nashville. Making design feel approachable.",
    avatarUrl: null,
    avatarColor: "linear-gradient(135deg,#C4B5E0,#8870c0)",
    initials: "CF",
    topics: ["Design", "Interior"],
    socials: [{ label: "IG @caitlinflemming", url: "https://instagram.com/caitlinflemming" }],
    postCount: 4,
  },
  {
    id: "anh-sundstrom",
    name: "Anh Sundstrom",
    handle: "@9to5chic",
    followers: "381K",
    bio: "Fashion blogger turned style philosopher. Capsule wardrobes, quiet luxury, and dressing with intention since 2009.",
    avatarUrl: "https://9to5chic.com/wp-content/uploads/2016/10/DSC_0332-copy-3.jpg",
    avatarColor: null,
    initials: "AS",
    topics: ["Fashion", "Lifestyle"],
    socials: [{ label: "IG @9to5chic", url: "https://instagram.com/9to5chic" }, { label: "9to5chic.com", url: "https://9to5chic.com" }],
    postCount: 11,
  },
] as const;

export type Creator = (typeof CREATORS)[number];

// ── CONTENT (Edition stories) ─────────────────────────────────────────────────
export const CONTENT_ITEMS = [
  {
    id: "cadbury-protein-balls",
    creatorId: "nicole-keshishian",
    creatorName: "Nicole Keshishian",
    topics: ["Nutrition", "Recipes"],
    title: "Viral Cadbury Egg Protein Balls",
    description: "These no-bake protein balls taste exactly like Cadbury Eggs — and they're actually good for you. Just 6 ingredients, 15 minutes, no oven required. Nicole's most-shared recipe of the year.",
    url: "https://kalejunkie.com/viral-cadbury-egg-protein-balls/",
    imageUrl: "https://kalejunkie.com/wp-content/uploads/2026/03/KJ-Viral-Cadbury-Egg-Protein-Balls-6-scaled.jpg",
    format: "Article",
    date: "April 10, 2026",
    likes: 48,
    comments: 12,
  },
  {
    id: "minimalist-makeup",
    creatorId: "shira-gill",
    creatorName: "Shira Gill",
    topics: ["Lifestyle", "Wellness"],
    title: "My Favorite Minimalist Makeup and Skincare Essentials",
    description: "Shira's pared-down beauty routine: the 7 products she actually uses every day, why she ditched her 12-step routine, and the one face oil she'll never give up.",
    url: "https://shiragill.com/my-favorite-minimalist-makeup-and-skincare-essentials/",
    imageUrl: null,
    imageEmoji: "🪞",
    imageColor: "linear-gradient(135deg,#CCCEEF,#9095d0)",
    format: "Article",
    date: "April 9, 2026",
    likes: 31,
    comments: 7,
  },
  {
    id: "sunday-reset",
    creatorId: "amy-motroni",
    creatorName: "Amy Motroni",
    topics: ["Parenthood", "Wellness"],
    title: "Set Your Week Up For Success With a Sunday Reset Routine",
    description: "The exact 2-hour Sunday reset Amy swears by — meal prep, schedule blocking, and the one ritual that makes Monday mornings actually manageable.",
    url: "https://geniusmomhacks.com/sunday-reset-routine/",
    imageUrl: null,
    imageEmoji: "📅",
    imageColor: "linear-gradient(135deg,#F7D4A8,#d89848)",
    format: "Article",
    date: "April 8, 2026",
    likes: 19,
    comments: 4,
  },
  {
    id: "protocol-over-40",
    creatorId: "kate-ogata",
    creatorName: "Kate Ogata",
    topics: ["Fitness", "Wellness"],
    title: "The 20-Minute Protocol I Give Every Client Over 40",
    description: "Kate's signature strength protocol for women in their 40s and beyond: why you're probably lifting wrong, the two moves she always cuts, and what actually moves the needle.",
    url: "#",
    imageUrl: null,
    imageEmoji: "💪",
    imageColor: "linear-gradient(135deg,#B5D5F7,#6098d8)",
    format: "Social Post",
    date: "April 7, 2026",
    likes: 55,
    comments: 18,
  },
  {
    id: "10m-business",
    creatorId: "brit-morin",
    creatorName: "Brit Morin",
    topics: ["Entrepreneurship"],
    title: "How I Built a $10M Business While Raising Two Kids",
    description: "Brit gets unusually candid about the season she almost quit, the model change that saved Brit + Co, and why she stopped trying to be everywhere at once.",
    url: "#",
    imageUrl: null,
    imageEmoji: "🎙️",
    imageColor: "linear-gradient(135deg,#84B59F,#4a8068)",
    format: "Podcast",
    date: "April 6, 2026",
    likes: 24,
    comments: 9,
  },
  {
    id: "items-removing",
    creatorId: "holly-blakey",
    creatorName: "Holly Blakey",
    topics: ["Design", "Home"],
    title: "The 10 Items I'm Removing From Every Room This Month",
    description: "Holly's monthly ruthless edit — the specific pieces that are making your home feel smaller and more chaotic than it needs to, and what to replace them with.",
    url: "#",
    imageUrl: null,
    imageEmoji: "🏡",
    imageColor: "linear-gradient(135deg,#f5e8d8,#c8a870)",
    format: "Article",
    date: "April 5, 2026",
    likes: 37,
    comments: 14,
  },
  {
    id: "white-walls",
    creatorId: "caitlin-flemming",
    creatorName: "Caitlin Flemming",
    topics: ["Design", "Interior"],
    title: "Why I Stopped Painting My Walls White (And What I Use Instead)",
    description: "Caitlin's case for warm, grounded walls — the 3 colors she recommends for every room type and why the all-white trend was setting us up to fail.",
    url: "#",
    imageUrl: null,
    imageEmoji: "🎨",
    imageColor: "linear-gradient(135deg,#C4B5E0,#8870c0)",
    format: "Article",
    date: "April 4, 2026",
    likes: 29,
    comments: 11,
  },
  {
    id: "get-dressed-10min",
    creatorId: "anh-sundstrom",
    creatorName: "Anh Sundstrom",
    topics: ["Fashion", "Lifestyle"],
    title: "How I Get Dressed in 10 Minutes and Always Look Pulled Together",
    description: "Anh's capsule approach: the 8-piece formula she uses every season, and why she stopped buying anything that doesn't work with everything else in her closet.",
    url: "#",
    imageUrl: null,
    imageEmoji: "👗",
    imageColor: "linear-gradient(135deg,#f5d4d0,#c08078)",
    format: "Article",
    date: "April 3, 2026",
    likes: 42,
    comments: 16,
  },
] as const;

export type ContentItem = (typeof CONTENT_ITEMS)[number];

// ── MEMBERS ───────────────────────────────────────────────────────────────────
export const MEMBERS = [
  { id: "jennifer-l", name: "Jennifer L.", location: "Mill Valley, CA",   topics: ["Design", "Wellness"],         initials: "J", avatarColor: "linear-gradient(135deg,#CCCEEF,#9095d0)", benchCount: 7 },
  { id: "sarah-c",   name: "Sarah C.",    location: "San Francisco, CA",  topics: ["Nutrition", "Fitness"],        initials: "S", avatarColor: "linear-gradient(135deg,#FE9D94,#e07868)", benchCount: 12 },
  { id: "maria-b",   name: "Maria B.",    location: "Marin, CA",          topics: ["Perimenopause"],               initials: "M", avatarColor: "linear-gradient(135deg,#84B59F,#4a8068)", benchCount: 4 },
  { id: "rachel-t",  name: "Rachel T.",   location: "Tiburon, CA",        topics: ["Entrepreneurship", "Finance"], initials: "R", avatarColor: "linear-gradient(135deg,#F7D4A8,#d89848)", benchCount: 9 },
  { id: "lauren-k",  name: "Lauren K.",   location: "Ross, CA",           topics: ["Fashion", "Lifestyle"],        initials: "L", avatarColor: "linear-gradient(135deg,#C4B5E0,#8870c0)", benchCount: 6 },
  { id: "amanda-w",  name: "Amanda W.",   location: "San Anselmo, CA",    topics: ["Nutrition", "Wellness"],       initials: "A", avatarColor: "linear-gradient(135deg,#F5C0B8,#d07870)", benchCount: 11 },
  { id: "katherine-m", name: "Katherine M.", location: "Mill Valley, CA", topics: ["Parenthood", "Design"],       initials: "K", avatarColor: "linear-gradient(135deg,#B5D5F7,#6098d8)", benchCount: 8 },
  { id: "nina-p",    name: "Nina P.",     location: "Sausalito, CA",      topics: ["Fitness"],                     initials: "N", avatarColor: "linear-gradient(135deg,#f0e0b0,#c8a840)", benchCount: 3 },
  { id: "emily-s",   name: "Emily S.",    location: "Corte Madera, CA",   topics: ["Real Estate", "Lifestyle"],    initials: "E", avatarColor: "linear-gradient(135deg,#d4e8d8,#78a880)", benchCount: 5 },
  { id: "claire-d",  name: "Claire D.",   location: "San Francisco, CA",  topics: ["Perimenopause", "Wellness"],   initials: "C", avatarColor: "linear-gradient(135deg,#e8c8e8,#b070b0)", benchCount: 14 },
] as const;

// ── TOPICS ────────────────────────────────────────────────────────────────────
export const ALL_TOPICS = [
  "Nutrition", "Recipes", "Perimenopause", "Wellness", "Fitness",
  "Parenthood", "Design", "Interior", "Home", "Lifestyle",
  "Fashion", "Entrepreneurship", "Finance", "Real Estate", "Travel",
  "Food", "Beauty",
] as const;

// ── BENCHES (seed state for the logged-in demo member) ─────────────────────
export const SEED_BENCHES = [
  {
    id: "morning-read",
    name: "Morning Read",
    visibility: "members" as const,
    creatorIds: ["nicole-keshishian", "shira-gill", "amy-motroni"],
    description: "My daily reads with coffee.",
  },
  {
    id: "design-home",
    name: "Design + Home",
    visibility: "members" as const,
    creatorIds: ["holly-blakey", "caitlin-flemming"],
    description: "All things interior and home.",
  },
  {
    id: "wellness",
    name: "Wellness",
    visibility: "private" as const,
    creatorIds: ["kate-ogata", "shira-gill", "amy-motroni"],
    description: null,
  },
  {
    id: "founders",
    name: "Founders",
    visibility: "private" as const,
    creatorIds: ["brit-morin"],
    description: null,
  },
] as const;

export type SeedBench = (typeof SEED_BENCHES)[number];

// ── BUSINESS CATEGORIES ────────────────────────────────────────────────────
export const BIZ_CATEGORIES = [
  "Acupuncture", "Beauty", "Coaching", "Design", "Events",
  "Fashion", "Finance", "Fitness", "Food & Nutrition",
  "Interior Design", "Media", "Real Estate", "Retail", "Travel", "Wellness",
] as const;

export type BizCategory = (typeof BIZ_CATEGORIES)[number];

// ── BUSINESSES ─────────────────────────────────────────────────────────────
export const BUSINESSES = [
  {
    id: "kalejunkie",
    name: "Kalejunkie",
    ownerName: "Nicole Keshishian",
    ownerId: "nicole-keshishian",
    ownerType: "creator" as const,
    category: "Food & Nutrition" as BizCategory,
    categories: ["Food & Nutrition", "Wellness"] as BizCategory[],
    location: "Corte Madera, CA",
    tagline: "Nourishing recipes for real life.",
    description: "Kalejunkie is Nicole Keshishian's food and wellness brand, built around the belief that eating well should feel joyful, not punishing. Known for her vibrant, no-fuss recipes and The Kalejunkie Cookbook, Nicole has built one of the most trusted nutrition communities online.",
    website: "https://kalejunkie.com",
    socials: [
      { label: "IG @kalejunkie", url: "https://instagram.com/kalejunkie" },
      { label: "Substack", url: "#" },
    ],
    heroImage: "https://kalejunkie.com/wp-content/uploads/2025/09/main-image.webp",
    heroColor: null,
    heroEmoji: null,
    keyImage: "https://kalejunkie.com/wp-content/uploads/2026/03/KJ-Viral-Cadbury-Egg-Protein-Balls-6-scaled.jpg",
    keyColor: null,
    keyEmoji: null,
    founded: "2017",
  },
  {
    id: "shira-gill-studio",
    name: "Shira Gill Studio",
    ownerName: "Shira Gill",
    ownerId: "shira-gill",
    ownerType: "creator" as const,
    category: "Coaching" as BizCategory,
    categories: ["Coaching", "Wellness", "Design"] as BizCategory[],
    location: "Mill Valley, CA",
    tagline: "Simplify your home, wardrobe, and life.",
    description: "Shira Gill Studio offers organizing consultations, online courses, and workshops for women who want to live with less and love it. Shira is the author of two books on minimalism and has been featured in Real Simple, Martha Stewart Living, and The New York Times.",
    website: "https://shiragill.com",
    socials: [
      { label: "IG @shiragill", url: "https://instagram.com/shiragill" },
    ],
    heroImage: "https://shiragill.com/wp-content/uploads/BeccaMeyerMillValley_7036-Edita-scaled.jpg",
    heroColor: null,
    heroEmoji: null,
    keyImage: null,
    keyColor: "linear-gradient(135deg,#CCCEEF,#9095d0)",
    keyEmoji: "✨",
    founded: "2015",
  },
  {
    id: "breathing-room",
    name: "Breathing Room",
    ownerName: "Holly Blakey",
    ownerId: "holly-blakey",
    ownerType: "creator" as const,
    category: "Interior Design" as BizCategory,
    categories: ["Interior Design", "Design"] as BizCategory[],
    location: "San Francisco, CA",
    tagline: "Calm, intentional homes for women done with clutter.",
    description: "Breathing Room is Holly Blakey's full-service interior design practice focused on creating serene, livable homes. Holly specializes in editing down — removing what doesn't serve you and elevating what does. Based in SF with projects across the Bay Area and beyond.",
    website: "https://breathingroom.com",
    socials: [
      { label: "IG @breathing.room.home", url: "https://instagram.com/breathing.room.home" },
    ],
    heroImage: "https://static1.squarespace.com/static/5b0b65b8f407b4a4414db2ee/5ea6de0a41e9232ab0a8b58d/639fd7597ca60c5b989498a5/1713378056113/Holly+June+20220467.jpg?format=1500w",
    heroColor: null,
    heroEmoji: null,
    keyImage: null,
    keyColor: "linear-gradient(135deg,#f5e8d8,#c8a870)",
    keyEmoji: "🏡",
    founded: "2016",
  },
  {
    id: "brit-co",
    name: "Brit + Co",
    ownerName: "Brit Morin",
    ownerId: "brit-morin",
    ownerType: "creator" as const,
    category: "Media" as BizCategory,
    categories: ["Media", "Fashion", "Design"] as BizCategory[],
    location: "San Francisco, CA",
    tagline: "Empowering women to build brands they're proud of.",
    description: "Brit + Co is a lifestyle media company and learning platform founded by Brit Morin. From online courses to editorial content and investor coaching, Brit + Co helps women at every stage — from side hustle to scale. Brit is also a seed investor in over 80 companies.",
    website: "https://brit.co",
    socials: [
      { label: "IG @brit", url: "https://instagram.com/brit" },
    ],
    heroImage: "https://images.squarespace-cdn.com/content/v1/6303fb9404a0cf0cd130ef3c/f7b9ac1c-b3cb-42e6-aa9d-982f34d5507a/Brit+Morin+Headshot.jpg",
    heroColor: null,
    heroEmoji: null,
    keyImage: null,
    keyColor: "linear-gradient(135deg,#84B59F,#4a8068)",
    keyEmoji: "🎙️",
    founded: "2011",
  },
  {
    id: "caitlin-flemming-interiors",
    name: "Caitlin Flemming Interiors",
    ownerName: "Caitlin Flemming",
    ownerId: "caitlin-flemming",
    ownerType: "creator" as const,
    category: "Interior Design" as BizCategory,
    categories: ["Interior Design", "Design"] as BizCategory[],
    location: "Nashville, TN",
    tagline: "Warm, livable design that feels like home.",
    description: "Caitlin Flemming Interiors is a full-service residential design studio based in Nashville. Caitlin's approach blends warmth, texture, and practicality — beautiful rooms that actually get lived in. She works on projects across the Southeast and takes on select remote consultations.",
    website: "https://caitlinflemming.com",
    socials: [
      { label: "IG @caitlinflemming", url: "https://instagram.com/caitlinflemming" },
    ],
    heroImage: null,
    heroColor: "linear-gradient(135deg,#C4B5E0,#8870c0)",
    heroEmoji: null,
    keyImage: null,
    keyColor: "linear-gradient(135deg,#C4B5E0,#8870c0)",
    keyEmoji: "🎨",
    founded: "2018",
  },
  {
    id: "soleil-wellness",
    name: "Soleil Wellness Studio",
    ownerName: "Amara Klein",
    ownerId: null,
    ownerType: "member" as const,
    category: "Fitness" as BizCategory,
    categories: ["Fitness", "Wellness"] as BizCategory[],
    location: "Mill Valley, CA",
    tagline: "Movement, breath, and belonging.",
    description: "Soleil is a boutique wellness studio in the heart of Mill Valley offering yoga, Pilates, breathwork, and women's wellness workshops. Small classes, intentional community. Founded by longtime Marin resident Amara Klein, a 500-hour RYT and certified Pilates instructor.",
    website: "#",
    socials: [
      { label: "IG @soleilwellness", url: "#" },
    ],
    heroImage: null,
    heroColor: "linear-gradient(135deg,#FE9D94,#e07868)",
    heroEmoji: null,
    keyImage: null,
    keyColor: "linear-gradient(135deg,#FE9D94,#e07868)",
    keyEmoji: "🧘",
    founded: "2020",
  },
  {
    id: "the-wardrobe-edit",
    name: "The Wardrobe Edit",
    ownerName: "Margot Ellison",
    ownerId: null,
    ownerType: "member" as const,
    category: "Fashion" as BizCategory,
    categories: ["Fashion", "Retail", "Coaching"] as BizCategory[],
    location: "Sausalito, CA",
    tagline: "Style consulting and capsule wardrobe curation.",
    description: "The Wardrobe Edit offers personal styling sessions, wardrobe audits, and curated shopping services for women who want to look pulled-together without trying too hard. Based in Sausalito with virtual sessions available worldwide.",
    website: "#",
    socials: [
      { label: "IG @thewardrobeedit", url: "#" },
    ],
    heroImage: null,
    heroColor: "linear-gradient(135deg,#f5d4d0,#c08078)",
    heroEmoji: null,
    keyImage: null,
    keyColor: "linear-gradient(135deg,#f5d4d0,#c08078)",
    keyEmoji: "👗",
    founded: "2021",
  },
  {
    id: "roots-ritual-events",
    name: "Roots & Ritual Events",
    ownerName: "Danielle Park",
    ownerId: null,
    ownerType: "member" as const,
    category: "Events" as BizCategory,
    categories: ["Events"] as BizCategory[],
    location: "San Francisco, CA",
    tagline: "Intentional gatherings for women who lead.",
    description: "Roots & Ritual designs intimate events, retreats, and community experiences for women executives and founders. From offsite strategy days to celebration dinners, every event is crafted to feel meaningful, not transactional.",
    website: "#",
    socials: [
      { label: "IG @rootsandritual", url: "#" },
    ],
    heroImage: null,
    heroColor: "linear-gradient(135deg,#84B59F,#4a8068)",
    heroEmoji: null,
    keyImage: null,
    keyColor: "linear-gradient(135deg,#84B59F,#4a8068)",
    keyEmoji: "🌿",
    founded: "2022",
  },
  {
    id: "marin-acupuncture",
    name: "Marin Acupuncture & Wellness",
    ownerName: "Dr. Soo-Jin Park",
    ownerId: null,
    ownerType: "member" as const,
    category: "Acupuncture" as BizCategory,
    categories: ["Acupuncture", "Wellness"] as BizCategory[],
    location: "San Rafael, CA",
    tagline: "Whole-body care rooted in Chinese medicine.",
    description: "Marin Acupuncture & Wellness is a women-centered integrative health practice specializing in acupuncture, herbal medicine, and holistic care for hormonal health, perimenopause, anxiety, and chronic pain. Dr. Soo-Jin Park has practiced for 18 years.",
    website: "#",
    socials: [
      { label: "IG @marinacupuncture", url: "#" },
    ],
    heroImage: null,
    heroColor: "linear-gradient(135deg,#B5D5F7,#6098d8)",
    heroEmoji: null,
    keyImage: null,
    keyColor: "linear-gradient(135deg,#B5D5F7,#6098d8)",
    keyEmoji: "🌸",
    founded: "2006",
  },
  {
    id: "altitude-travel",
    name: "Altitude Travel",
    ownerName: "Claire Beaumont",
    ownerId: null,
    ownerType: "member" as const,
    category: "Travel" as BizCategory,
    categories: ["Travel"] as BizCategory[],
    location: "Mill Valley, CA",
    tagline: "Bespoke travel for women who know what they want.",
    description: "Altitude Travel plans private, fully-customized journeys for high-achieving women and small groups. Specialties include Italy, Japan, the American Southwest, and women's adventure trips. No generic itineraries — every trip is built from scratch.",
    website: "#",
    socials: [
      { label: "IG @altitudetravel", url: "#" },
    ],
    heroImage: null,
    heroColor: "linear-gradient(135deg,#F7D4A8,#d89848)",
    heroEmoji: null,
    keyImage: null,
    keyColor: "linear-gradient(135deg,#F7D4A8,#d89848)",
    keyEmoji: "✈️",
    founded: "2019",
  },
  {
    id: "maven-financial",
    name: "Maven Financial Advisory",
    ownerName: "Rachel Torres",
    ownerId: null,
    ownerType: "member" as const,
    category: "Finance" as BizCategory,
    categories: ["Finance"] as BizCategory[],
    location: "San Francisco, CA",
    tagline: "Financial planning for women navigating transition.",
    description: "Maven Financial Advisory works exclusively with women in major life transitions — divorce, inheritance, career change, or building a business. CFP Rachel Torres founded Maven after spending 12 years at a large firm, frustrated by the lack of nuanced, judgment-free guidance for women.",
    website: "#",
    socials: [
      { label: "LI Maven Financial", url: "#" },
    ],
    heroImage: null,
    heroColor: "linear-gradient(135deg,#e8c8e8,#b070b0)",
    heroEmoji: null,
    keyImage: null,
    keyColor: "linear-gradient(135deg,#e8c8e8,#b070b0)",
    keyEmoji: "📊",
    founded: "2020",
  },
] as const;

export type Business = (typeof BUSINESSES)[number];
